kind: Deployment
apiVersion: apps/v1
metadata:
  name: php-fpm
  namespace: demo
spec:
  selector:
    matchLabels:
      app: php-fpm
  replicas: 3
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      containers:
        - name: php-fpm
          image: lufeijun1234/php-fpm:8.1.19
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
---
kind: Service
apiVersion: v1
metadata:
  name: php-fpm-svc
  namespace: demo
spec:
  selector:
    app: php-fpm
  ports:
    - port: 9000
      targetPort: 9000