apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: demo
  labels:
    nginx-pod-labels: nginx
  annotations:
    name: nginx-pod-annotation
spec:
  containers:
    - name: nginx-pod
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - name: httpd
          containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: nginx-site   #使用的存储卷名称，跟下面volume字段的某个name值相同，这里表示使用volume的nginx-site这个存储卷
          mountPath: /usr/share/nginx/html  #挂载至容器中哪个目录
          readOnly: false                   #读写挂载方式，默认为读写模式false
        - name: nginx-log
          mountPath: /var/log/nginx/
          readOnly: false
  volumes:              #volumes字段定义了paues容器关联的宿主机或分布式文件系统存储卷
    - name: nginx-site    #存储卷名称
      hostPath:           #路径，为宿主机存储路径
        path: /data/k8s/volumes/nginx/html/   #在宿主机上目录的路径
        type: DirectoryOrCreate           #定义类型，这表示如果宿主机没有此目录，则会自动创建
    - name: nginx-log
      hostPath:
        path: /data/k8s/volumes/nginx/log/
        type: DirectoryOrCreate