apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        readinessProbe:
          failureThreshold: 3 #当 Pod 启动了并且探测到失败，Kubernetes 的重试次数
          httpGet:
            path: /index.html
            port: nginx-port
            scheme: HTTP
          initialDelaySeconds: 10  #容器启动后第一次执行探测是需要等待多少秒
          periodSeconds: 10   #执行探测的频率，默认是10秒，最小1秒
          successThreshold: 1 #探测失败后，最少连续探测成功多少次才被认定为成功
          timeoutSeconds: 10 #探测超时时间，默认1秒，最小1秒
        livenessProbe:
          failureThreshold: 3 #当 Pod 启动了并且探测到失败，Kubernetes 的重试次数
          httpGet:
            path: /index.html
            port: nginx-port
            scheme: HTTP
          initialDelaySeconds: 10  #容器启动后第一次执行探测是需要等待多少秒
          periodSeconds: 10   #执行探测的频率，默认是10秒，最小1秒
          successThreshold: 1 #探测失败后，最少连续探测成功多少次才被认定为成功
          timeoutSeconds: 10 #探测超时时间，默认1秒，最小1秒
        ports:
        - containerPort: 80
          name: nginx-port
---
apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: nginx-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30036