apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: go-zero
  name: deployment
spec:
  selector:
    matchLabels:
      app: go-zero
  replicas: 3
  strategy: # 更新策略
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: go-zero
    spec:
      containers:
      - name: go-zero
        image: lufeijun1234/docker-go-zero-demo
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: env  # 挂载数据卷 (要跟下面的 name 名字相同)
          mountPath: /app/etc
          readOnly: true
      volumes:
      - name: env   # 创建一个数据卷
        configMap:  # ConfigMap 方式
          name: go-zero-config   
---
apiVersion: v1
kind: Service
metadata:
  namespace: go-zero
  name: service
spec:
  selector:
    app: go-zero
  type: NodePort
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 30088