# 没有 selector 的，用于指定外部资源

apiVersion: v1
kind: Service
metadata:
  name: out-nginx-service-01
  namespace: demo
spec:
  ports:
    - protocol: TCP
      port: 9090
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: out-nginx-service-01 # 按惯例将服务的名称用作 EndpointSlice 名称的前缀
  namespace: demo
  labels:
    kubernetes.io/service-name: out-nginx-service-01 # 你应设置 "kubernetes.io/service-name" 标签。设置其值以匹配服务的名称
addressType: IPv4
ports:
  - name: '' # 留空，因为 port 9090 未被 IANA 分配为已注册端口
    appProtocol: http
    protocol: TCP
    port: 8888
endpoints:
  - addresses:
      - "192.168.0.22" # 此列表中的 IP 地址可以按任何顺序显示
    conditions:
      ready: true  
  - addresses:
      - "192.168.0.155" # 此列表中的 IP 地址可以按任何顺序显示"
    conditions:
      ready: true  
