# 引入外部资源
# 通过定义 service 和 endpoints 对象
apiVersion: v1
kind: Service
metadata:
  name: out-nginx-service-02               #service的名称叫做outside-agent-svc
  namespace: demo
spec:
  ports:
  - name: out-nginx-port-02               #service端口的名称
    port: 9090                            #service的端口
    protocol: TCP                        #端口协议
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: out-nginx-service-02              #endpoint的名称一定要与service的名称一致
  namespace: demo
subsets:
- addresses:
  - ip: 192.168.0.155                    #定义外部服务地址
  - ip: 192.168.0.22                    #定义外部服务地址
  ports:
  - port: 8888                          #外部服务的端口
    name: out-nginx-port-02                #端口的name，这个名称一定要与service端口的名称
    protocol: TCP                        #端口协议，这个协议一定要与service的端口协议一致